blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Ask a Question
    url: https://github.com/slspinola/apphub/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“– Documentation
    url: https://github.com/slspinola/apphub/blob/master/README.md
    about: Check the project documentation

